# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53372ca0e91e4aabe93e78b157ef0e7c22b33ada62217991e1bca2ebed00937692d1513ed307ef0a1af62e259511e9eeb6fc1fcc3c0c51f06ece1ca844a1fc8d

test:
  secret_key_base: 3eac6e64d87f02ef5fc1c682d210a63e48c6f41be587ddea81b66abfcc45f91226644a7acc4f236ff43ac61752328a2caeb970759176c813a062251a12b7189f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
